"""Initial Schema

Revision ID: cac529629b44
Revises: 
Create Date: 2026-07-03 13:02:39.904584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac529629b44'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.Enum('IT', 'FINANCE', 'HEALTHCARE', 'EDUCATION', 'MANUFACTURING', 'OTHER', name='industryenum'), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('company_size', sa.Enum('STARTUP', 'SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE', name='companysizeenum'), nullable=False),
    sa.Column('gst_number', sa.String(length=30), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('subdomain', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statusenum'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gst_number'),
    sa.UniqueConstraint('subdomain')
    )
    op.create_index('idx_company_email', 'organizations', ['company_email'], unique=False)
    op.create_index('idx_company_name', 'organizations', ['company_name'], unique=False)
    op.create_index('idx_subdomain', 'organizations', ['subdomain'], unique=False)
    op.create_index(op.f('ix_organizations_company_email'), 'organizations', ['company_email'], unique=True)
    op.create_index(op.f('ix_organizations_company_name'), 'organizations', ['company_name'], unique=False)
    op.create_table('roles',
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statusenum'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_index('idx_role_name', 'roles', ['role_name'], unique=False)
    op.create_table('departments',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('department_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_organization_id'), 'departments', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_organization_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index('idx_role_name', table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_organizations_company_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_company_email'), table_name='organizations')
    op.drop_index('idx_subdomain', table_name='organizations')
    op.drop_index('idx_company_name', table_name='organizations')
    op.drop_index('idx_company_email', table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
