"""Create Permission Table

Revision ID: cf0487f0975d
Revises: cac529629b44
Create Date: 2026-07-03 13:05:48.202671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf0487f0975d'
down_revision: Union[str, Sequence[str], None] = 'cac529629b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('permission_code', sa.String(length=100), nullable=False),
    sa.Column('permission_name', sa.String(length=150), nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='statusenum'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_code')
    )
    op.create_index('idx_permission_code', 'permissions', ['permission_code'], unique=False)
    op.create_index('idx_permission_module', 'permissions', ['module_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_permission_module', table_name='permissions')
    op.drop_index('idx_permission_code', table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
